CREATE TABLE employee (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL DEFAULT NULL,
first_name TEXT NOT NULL DEFAULT NULL,
last_name TEXT NOT NULL DEFAULT NULL,
eid TEXT NOT NULL DEFAULT NULL,
email TEXT NOT NULL DEFAULT NULL
);
